#!/bin/bash

if [[ $# != 1 ]] || ([[ $1 != "--hard" ]] && [[ $1 != "--soft" ]]);then
    echo "Usage: require-sudo (--soft | --hard)
    
    --soft Just checks sudo access
    --hard Check run as sudo"
fi

if [[ $1 == "--soft" ]] && [[ $(sudo echo 0) ]];then
    echo "Success!";
    exit
fi

if [[ $1 == "--hard" ]] && [[ $(sudo echo 0) ]] && [[ $UID == 0 ]];then
    echo "Success!";
    exit
fi

echo "Fail!"
